import type { Basis, Confidence, HalalStatus, IngredientEntry, MatchResult } from '@/types';

/**
 * Layer 1b: keyword curation rules.
 *
 * These catch label wordings that never appear in ingredient datasets (Japanese
 * local naming like 動物性エキス or 料理酒) and act as a fallback when the
 * curated table has no exact entry. Rules run on NORMALIZED text (see
 * normalize.ts: lowercased, punctuation/space stripped), so patterns are plain
 * substrings.
 *
 * Order matters: more specific rules must come first. The generic エキス rule is
 * deliberately last among extracts — a curated exact entry (e.g. 酵母エキス,
 * halal) is matched before rules are consulted, so it is never overridden.
 */
export interface CurationRule {
  id: string;
  label: string;
  status: HalalStatus;
  confidence: Confidence;
  category: string;
  patterns: RegExp[];
  reasoning: string;
  sources: string[];
  /** Defaults to 'japan-label-rule' when omitted. */
  basis?: Basis;
}

/** Shorthand for the many "common, clearly plant/mineral" ingredient rules. */
function halalRule(
  id: string,
  label: string,
  patterns: RegExp[],
  category: string,
  reasoning: string,
  confidence: Confidence = 'high'
): CurationRule {
  return {
    id,
    label,
    status: 'halal',
    confidence,
    category,
    patterns,
    reasoning,
    sources: ['LPPOM MUI — bahan nabati/mineral', 'JAKIM MS1500:2019'],
  };
}

const LPPOM = 'LPPOM MUI — kriteria bahan';
const JAKIM = 'JAKIM MS1500:2019';

export const CURATION_RULES: CurationRule[] = [
  {
    id: 'sake',
    label: 'Sake / 清酒',
    status: 'haram',
    confidence: 'high',
    category: 'alcohol',
    patterns: [/日本酒/, /清酒/, /せいしゅ/],
    reasoning:
      'Sake/清酒 adalah minuman khamr berbasis beras yang memabukkan, haram.',
    sources: ["QS Al-Maa'idah 5:90", LPPOM],
  },
  {
    id: 'pork',
    label: 'Pork / 豚肉',
    status: 'haram',
    confidence: 'high',
    category: 'animal',
    patterns: [/豚肉/, /ぶたにく/, /ポーク/, /ラード/, /豚脂/, /豚エキス/, /豚肉エキス/, /豚骨/, /豚ガラ/],
    reasoning: 'Berasal dari babi (daging/lemak/ekstrak). Haram secara eksplisit.',
    sources: ['QS Al-Baqarah 2:173', LPPOM],
  },
  {
    id: 'mirin',
    label: 'Mirin / 料理酒',
    status: 'syubhat',
    confidence: 'medium',
    category: 'alcohol',
    patterns: [/本みりん/, /みりん/, /味醂/, /料理酒/, /調理酒/],
    reasoning:
      'Mirin/料理酒 adalah bumbu masak beralkohol (beras). Banyak fatwa mengharamkan; "みりん風調味料" (rendah alkohol) pun tetap perlu verifikasi.',
    sources: [LPPOM, JAKIM],
  },
  {
    id: 'sake-lees',
    label: 'Sake lees / 酒粕',
    status: 'syubhat',
    confidence: 'medium',
    category: 'alcohol',
    patterns: [/酒粕/, /酒糟/, /さけかす/, /酒粕パウダー/],
    reasoning:
      '酒粕 (sake lees) adalah hasil samping fermentasi sake dan dapat masih mengandung residu alkohol. Minimal syubhat. Catatan: bisa ter-tag vegan di Open Food Facts (fermentasi beras) tetapi itu hanya soal sumber hewani, bukan bebas alkohol.',
    sources: [LPPOM, JAKIM],
  },
  {
    id: 'cochineal',
    label: 'Cochineal / コチニール色素',
    status: 'syubhat',
    confidence: 'medium',
    category: 'colorant',
    patterns: [/コチニール/, /カルミン/, /カルミン酸/],
    reasoning:
      'Pewarna dari serangga cochineal (E120). Ulama berbeda pendapat; sebagian menghindari. Umum di kamaboko/produk merah muda Jepang.',
    sources: ['EFSA — E120', LPPOM],
  },
  {
    id: 'animal-extract',
    label: 'Animal extract / 動物性エキス',
    status: 'syubhat',
    confidence: 'medium',
    category: 'animal',
    patterns: [
      /動物性エキス/,
      /動物エキス/,
      /肉エキス/,
      /チキンエキス/,
      /ビーフエキス/,
      /魚介エキス/,
      /煮干しエキス/,
    ],
    reasoning:
      'Ekstrak hewani tanpa keterangan spesies/sembelihan. Sumber tidak dapat dipastikan, sehingga syubhat.',
    sources: [LPPOM, JAKIM],
  },
  {
    id: 'gelatin',
    label: 'Gelatin / ゼラチン',
    status: 'syubhat',
    confidence: 'medium',
    category: 'animal',
    patterns: [/ゼラチン/, /コラーゲン/],
    reasoning:
      'Gelatin/kolagen bisa dari babi (haram), sapi syar\'i (halal), atau ikan. Tanpa keterangan sumber, syubhat.',
    sources: [LPPOM, JAKIM],
  },
  {
    id: 'rennet-pepsin',
    label: 'Rennet / pepsin',
    status: 'syubhat',
    confidence: 'medium',
    category: 'enzyme',
    patterns: [/レンネット/, /レンニン/, /ペプシン/, /トランスグルタミナーゼ/],
    reasoning:
      'Enzim dapat berasal dari hewan (termasuk babi) atau mikroba. Sumber menentukan status; tanpa keterangan syubhat.',
    sources: [LPPOM, JAKIM],
  },
  {
    id: 'l-cysteine',
    label: 'L-cysteine / システイン',
    status: 'syubhat',
    confidence: 'medium',
    category: 'additive',
    patterns: [/システイン/],
    reasoning:
      'L-sistein dapat berasal dari rambut/bulu/plasma hewani atau sintetis/mikroba. Tanpa keterangan syubhat.',
    sources: ['EFSA — E920', LPPOM],
  },
  {
    id: 'white-dashi',
    label: 'Shiro-dashi / 白だし',
    status: 'syubhat',
    confidence: 'medium',
    category: 'seasoning',
    patterns: [/白だし/],
    reasoning:
      '白だし sering mengandung mirin/alkohol dan ekstrak hewani. Perlu verifikasi sertifikasi.',
    sources: [LPPOM, JAKIM],
  },
  {
    id: 'emulsifier',
    label: 'Emulsifier / 乳化剤',
    status: 'syubhat',
    confidence: 'medium',
    category: 'additive',
    patterns: [/乳化剤/],
    reasoning:
      'Emulsifier bisa nabati (halal), sapi syar\'i (halal), atau babi (haram). Tanpa keterangan sumber syubhat.',
    sources: ['EFSA — E471/E322', LPPOM],
  },
  {
    id: 'shortening',
    label: 'Shortening / ショートニング',
    status: 'syubhat',
    confidence: 'medium',
    category: 'fat',
    patterns: [/ショートニング/],
    reasoning:
      'Shortening adalah lemak terhidrogenasi, bisa berbasis hewani (termasuk babi) atau nabati.',
    sources: [LPPOM, JAKIM],
  },
  {
    id: 'flavoring',
    label: 'Flavoring / 香料',
    status: 'syubhat',
    confidence: 'low',
    category: 'additive',
    patterns: [/香料/],
    reasoning:
      'Perisa dapat mengandung pelarut alkohol atau turunan hewani. Perlu verifikasi.',
    sources: [LPPOM, JAKIM],
  },
  {
    id: 'alcohol',
    label: 'Alcohol / アルコール',
    status: 'syubhat',
    confidence: 'medium',
    category: 'alcohol',
    patterns: [/アルコール/, /エタノール/, /乙醇/],
    reasoning:
      'Alkohol/etanol sebagai pelarut atau aditif diperdebatkan antar ulama; label halal diperlukan.',
    sources: [LPPOM, JAKIM],
  },
  // --- common meats (halal if slaughtered per shariah; caveat noted) ---------
  {
    id: 'chicken',
    label: 'Chicken / チキン',
    status: 'syubhat',
    confidence: 'medium',
    category: 'animal',
    patterns: [/チキン/, /鶏肉/, /とりにく/, /鶏ささみ/, /若鶏/],
    reasoning: 'Daging ayam halal bila disembelih syar\'i, tetapi di Jepang umumnya tidak. Tanpa logo/sertifikasi halal, syubhat.',
    sources: ['QS Al-Baqarah 2:173 (prinsip)', JAKIM],
  },
  {
    id: 'beef',
    label: 'Beef / 牛肉',
    status: 'syubhat',
    confidence: 'medium',
    category: 'animal',
    patterns: [/ビーフ/, /牛肉/, /牛脂/, /ヘット/],
    reasoning: 'Daging/lemak sapi halal bila disembelih syar\'i, tetapi di Jepang umumnya tidak. Tanpa sertifikasi halal, syubhat.',
    sources: ['QS Al-Baqarah 2:173 (prinsip)', JAKIM],
  },
  {
    id: 'lamb',
    label: 'Lamb / 羊肉',
    status: 'syubhat',
    confidence: 'medium',
    category: 'animal',
    // NB: never bare /ラム/ — it matches グラム (gram). Require a meat context.
    patterns: [/ラム肉/, /ラムチョップ/, /羊肉/, /マトン/],
    reasoning: 'Daging kambing/domba halal bila disembelih syar\'i, tetapi di Jepang umumnya tidak. Tanpa sertifikasi halal, syubhat.',
    sources: ['QS Al-Baqarah 2:173 (prinsip)', JAKIM],
  },
  {
    id: 'fish',
    label: 'Fish / 魚',
    status: 'halal',
    confidence: 'medium',
    category: 'animal',
    patterns: [/魚/, /さかな/, /フィッシュ/, /白身魚/],
    reasoning: 'Ikan dan hasil laut pada dasarnya halal menurut mayoritas ulama.',
    sources: ["QS Al-Maa'idah 5:96", 'LPPOM MUI — hasil laut'],
  },
  {
    id: 'egg',
    label: 'Egg / 卵',
    status: 'halal',
    confidence: 'medium',
    category: 'animal',
    patterns: [/卵/, /たまご/, /玉子/, /鶏卵/],
    reasoning: 'Telur halal.',
    sources: ['LPPOM MUI — turunan hewani halal', JAKIM],
  },
  {
    id: 'milk',
    label: 'Milk / 牛乳',
    status: 'halal',
    confidence: 'medium',
    category: 'dairy',
    patterns: [/牛乳/, /ミルク/, /乳成分/, /乳成/, /生乳/],
    reasoning: 'Susu halal; waspadai enzim/rennet pada produk olahannya (lihat keju/rennet).',
    sources: ['LPPOM MUI — turunan susu', JAKIM],
  },

  // --- common plant / mineral ingredients (clearly halal) --------------------
  halalRule('garlic', 'Garlic / にんにく', [/にんにく/, /ニンニク/, /大蒜/], 'plant', 'Bawang putih (nabati), halal.'),
  halalRule('onion', 'Onion / 玉ねぎ', [/玉ねぎ/, /玉葱/, /たまねぎ/, /オニオン/], 'plant', 'Bawang bombai (nabati), halal.'),
  halalRule('ginger', 'Ginger / しょうが', [/しょうが/, /生姜/, /ショウガ/], 'plant', 'Jahe (nabati), halal.'),
  halalRule('carrot', 'Carrot / にんじん', [/にんじん/, /人参/, /ニンジン/], 'plant', 'Wortel (nabati), halal.'),
  halalRule('potato', 'Potato / じゃがいも', [/じゃがいも/, /ジャガイモ/, /馬鈴薯/], 'plant', 'Kentang (nabati), halal.'),
  halalRule('cabbage', 'Cabbage / キャベツ', [/キャベツ/], 'plant', 'Kubis (nabati), halal.'),
  halalRule('tomato', 'Tomato / トマト', [/トマト/], 'plant', 'Tomat (nabati), halal.'),
  halalRule('cucumber', 'Cucumber / きゅうり', [/きゅうり/, /胡瓜/, /キュウリ/], 'plant', 'Mentimun (nabati), halal.'),
  halalRule('lemon', 'Lemon / レモン', [/レモン/], 'plant', 'Lemon (nabati), halal.'),
  halalRule('wheat', 'Wheat / 小麦', [/小麦/, /こむぎ/], 'plant', 'Gandum (nabati), halal.'),
  halalRule('soybean', 'Soybean / 大豆', [/大豆/, /だいず/], 'plant', 'Kedelai (nabati), halal.'),
  halalRule('rice', 'Rice / 米', [/^米$/, /白米/, /玄米/, /米粉/, /お米/, /こめ/, /ライス/], 'plant', 'Beras (nabati), halal.'),
  halalRule('corn', 'Corn / とうもろこし', [/とうもろこし/, /コーン/, /玉蜀黍/], 'plant', 'Jagung (nabati), halal.'),
  halalRule('sesame', 'Sesame / ごま', [/ごま/, /胡麻/, /ゴマ/], 'plant', 'Wijen (nabati), halal.'),
  halalRule('mustard', 'Mustard / マスタード', [/マスタード/], 'plant', 'Moster (nabati), halal.'),
  halalRule('spices', 'Spices / 香辛料', [/香辛料/, /スパイス/, /胡椒/, /こしょう/, /コショウ/], 'plant', 'Rempah-rempah (nabati), halal.'),
  halalRule('acidulant', 'Acidulant / 酸味料', [/酸味料/], 'additive', 'Asam pengatur rasa, umumnya halal.'),
  halalRule('thickener', 'Thickener / 増粘多糖類', [/増粘多糖類/, /増粘剤/, /糊料/], 'additive', 'Penstabil/pengental polisakarida, umumnya nabati/mikroba, halal.'),
  halalRule('veg-oil', 'Vegetable oil / 植物油脂', [/植物油脂/, /植物油/, /サラダ油/], 'fat', 'Minyak nabati, halal.'),
  halalRule('starch', 'Starch / でん粉', [/でん粉/, /澱粉/, /デンプン/], 'plant', 'Pati nabati, halal.'),
  halalRule('mayonnaise', 'Mayonnaise / マヨネーズ', [/マヨネーズ/], 'condiment', 'Mayones umumnya dari telur+cuka, halal (waspadai aditif).', 'medium'),
  halalRule('bread', 'Bread / パン', [/パン/], 'grain', 'Roti umumnya halal, tetapi bisa mengandung shortening/margarin hewani — cek bila ada.', 'low'),
  halalRule('seasoning', 'Seasoning / 調味料', [/調味料/, /调味料/], 'additive', 'Bumbu/penyedap (mis. アミノ酸等). Umumnya halal, tetapi sebagian bisa berisi ekstrak hewani.', 'low'),

  // --- frozen / atatame (ready-meal) common items ----------------------------
  halalRule('organic-acid', 'Organic acid / 有機酸', [/有機酸/], 'additive', 'Asam organik (pengatur keasaman), halal.'),
  halalRule('dietary-fiber', 'Dietary fiber / 食物繊維', [/食物繊維/, /食物線維/], 'plant', 'Serat pangan, halal.'),
  halalRule('pepper2', 'Pepper / 胡椒', [/胡椒/, /胡線/, /胡織/], 'plant', 'Merica (nabati), halal.'),
  halalRule('spice2', 'Spice / 香辛', [/香辛/, /香平料/], 'plant', 'Rempah-rempah (nabati), halal.'),
  halalRule('breadcrumbs', 'Breadcrumbs / パン粉', [/パン粉/], 'grain', 'Tepung roti, halal.'),
  halalRule('phosphate', 'Phosphate / リン酸', [/リン酸/], 'additive', 'Garam fosfat (mineral), halal.'),
  halalRule('palm-oil', 'Palm oil / パーム油', [/パーム油/, /パーム/], 'fat', 'Minyak sawit (nabati), halal.'),
  halalRule('caramel', 'Caramel / カラメル', [/カラメル/], 'colorant', 'Karamel dari gula, halal.'),
  halalRule('chili', 'Chili / 唐辛子', [/唐辛子/, /とうがらし/, /トウガラシ/], 'plant', 'Cabai (nabati), halal.'),
  halalRule('ketchup', 'Ketchup / ケチャップ', [/ケチャップ/], 'condiment', 'Saus tomat, halal.'),
  halalRule('pickles', 'Pickles / ピクルス', [/ピクルス/], 'plant', 'Acar sayur, halal.'),
  halalRule('dextrin', 'Dextrin / デキストリン', [/デキストリン/], 'additive', 'Dekstrin dari pati, halal.'),
  halalRule('liquid-sugar', 'Liquid sugar / 液糖', [/液糖/, /果糖/, /ぶどう糖液糖/], 'sweetener', 'Gula cair / glukosa-fruktosa, halal.'),
  halalRule('sugar-variant', 'Sugar / 砂糖', [/沙糖/], 'sweetener', 'Gula (nabati), halal. Varian OCR 沙糖.'),
  halalRule('miso', 'Miso / 味噌', [/味噌/, /みそ/], 'fermented', 'Miso fermentasi kedelai; umumnya halal, waspadai residu alkohol.', 'low'),
  halalRule('butter', 'Butter / バター', [/バター/], 'dairy', 'Mentega dari susu, halal.', 'medium'),
  halalRule('cream', 'Cream / クリーム', [/生クリーム/, /クリーム/], 'dairy', 'Krim susu, halal.', 'medium'),
  halalRule('milk-powder', 'Milk powder / 粉乳', [/脱脂粉乳/, /全粉乳/, /粉乳/], 'dairy', 'Susu bubuk, halal.', 'medium'),
  halalRule('whey', 'Whey / ホエイ', [/ホエイ/, /乳清/], 'dairy', 'Whey dari susu; umumnya halal, waspadai rennet.', 'low'),
  halalRule('carrageenan', 'Carrageenan / カラギーナン', [/カラギーナン/], 'additive', 'Karagenan rumput laut, halal.'),
  halalRule('ph-adjuster', 'pH adjuster', [/ph調/], 'additive', 'Pengatur pH, umumnya halal.'),
  halalRule('antioxidant', 'Antioxidant / 酸化防止剤', [/酸化防止剤/, /抗氧化/], 'additive', 'Antioksidan, umumnya halal.'),
  halalRule('vitamin', 'Vitamin', [/ビタミン/, /ビタ三ン/, /vc/, /ve/], 'additive', 'Vitamin, halal.'),
  halalRule('shallot', 'Shallot / シャロット', [/シャロット/, /エシャロット/, /シヤロット/], 'plant', 'Bawang merah (nabati), halal.'),
  halalRule('star-anise', 'Star anise / スターアニス', [/スターアニス/, /スターニス/, /スター二ス/, /八角/], 'plant', 'Adas bintang (nabati), halal.'),
  halalRule('chili-powder', 'Chili powder / チリパウダー', [/チリパウダ/, /チリパウ/, /チリペッパー/], 'plant', 'Bubuk cabai (nabati), halal.'),
  halalRule('rapeseed-oil', 'Rapeseed oil / なたね油', [/なたね油/, /菜種油/, /キャノーラ油/], 'fat', 'Minyak kanola/rapeseed (nabati), halal.'),
  halalRule('curry-powder', 'Curry powder / カレー粉', [/カレー粉/, /カレーパウダー/], 'plant', 'Bumbu kari (rempah, nabati), halal.'),
  halalRule('chutney', 'Chutney / チャツネ', [/チャツネ/], 'condiment', 'Chatni (buah/sayur), halal.'),
  halalRule('silica', 'Silica / 二酸化ケイ素', [/二酸化ケイ素/, /酸化ケイ素/, /二酸化珪素/], 'additive', 'Silika (mineral), halal.'),
  halalRule('calcium', 'Calcium salt / 酸Ca', [/酸ca/, /炭酸/], 'additive', 'Garam kalsium (mineral), halal.'),
  halalRule('citric', 'Citric acid / クエン酸', [/クエン酸/, /クエン/, /柠檬酸/], 'additive', 'Asam sitrat, halal.'),
  halalRule('lactic-acid', 'Lactic acid / 乳酸', [/乳酸/], 'additive', 'Asam laktat (fermentasi), halal.'),
  halalRule('malic', 'Malic acid / リンゴ酸', [/リンゴ酸/, /りんご酸/], 'additive', 'Asam malat, halal.'),
  halalRule('amino-acid', 'Amino acid / アミノ酸', [/アミノ酸/, /ア三ノ酸/], 'additive', 'Asam amino penyedap, halal.'),
  halalRule('succinate', 'Succinate / コハク酸', [/コハク酸/, /八ク酸/], 'additive', 'Garam asam suksinat, halal.'),
  halalRule('nucleic', 'Nucleic acid / 核酸', [/核酸/], 'additive', 'Asam nukleat penyedap, halal.'),
  halalRule('plant-protein', 'Plant protein / 植物性たん白', [/植物性たん白/, /大豆たん白/], 'plant', 'Protein nabati, halal.'),
  halalRule('thickener2', 'Thickener / 増粘', [/増粘/, /増幹/, /增粘/, /多糖/, /多糖类/], 'additive', 'Pengental polisakarida, umumnya nabati/mikroba, halal.'),
  {
    id: 'soy-sauce-variant',
    label: 'Soy sauce / 醤油',
    status: 'syubhat',
    confidence: 'medium',
    category: 'fermented',
    patterns: [/醤油/, /酱油/, /しょうゆ/],
    reasoning: 'Kecap Jepang dapat mengandung alkohol dari fermentasi. Perlu verifikasi (menangkap varian seperti 添付醤油).',
    sources: [LPPOM, JAKIM],
  },
  {
    id: 'coloring',
    label: 'Colouring / 着色料',
    status: 'syubhat',
    confidence: 'low',
    category: 'colorant',
    patterns: [/着色料/],
    reasoning: 'Pewarna generik bisa nabati, sintetis, atau serangga/hewani (mis. cochineal). Perlu verifikasi.',
    sources: ['EFSA — pewarna', LPPOM],
  },
  {
    id: 'hydrolyzed-protein',
    label: 'Hydrolyzed protein / たん白加水分解物',
    status: 'syubhat',
    confidence: 'medium',
    category: 'additive',
    patterns: [/加水分解/, /たん白加水分解/, /タンパク加水分解/],
    reasoning: 'Protein terhidrolisis umumnya dari kedelai/jagung, tetapi bisa juga dari hewani. Perlu verifikasi.',
    sources: [LPPOM, JAKIM],
  },
  {
    id: 'margarine',
    label: 'Margarine / マーガリン',
    status: 'syubhat',
    confidence: 'medium',
    category: 'fat',
    patterns: [/マーガリン/],
    reasoning: 'Margarin bisa berbasis lemak hewani (termasuk babi) atau nabati. Perlu verifikasi.',
    sources: [LPPOM, JAKIM],
  },
  {
    id: 'sauce',
    label: 'Sauce / ソース',
    status: 'syubhat',
    confidence: 'low',
    category: 'condiment',
    patterns: [/ソース/],
    reasoning: 'Saus (mis. Worcestershire/中濃) bisa mengandung alkohol, ekstrak hewani, atau ikan. Perlu verifikasi.',
    sources: [LPPOM, JAKIM],
  },

  // --- instant noodles / snacks / bakery / sauces ----------------------------
  halalRule('raising-agent', 'Raising agent / 膨張剤', [/膨張剤/, /膨服剤/, /膨帳剤/, /ベーキングパウダー/, /炭酸水素/], 'additive', 'Pengembang (baking powder/soda), halal.'),
  halalRule('kansui', 'Kansui / かんすい', [/かんすい/, /カンスイ/], 'additive', 'Air alkali (kansui) untuk mi, mineral, halal.'),
  halalRule('pectin', 'Pectin / ペクチン', [/ペクチン/], 'additive', 'Pektin buah, halal.'),
  halalRule('agar', 'Agar / 寒天', [/寒天/], 'additive', 'Agar rumput laut, halal.'),
  halalRule('starch-syrup', 'Starch syrup / 水飴', [/水飴/, /水あめ/, /還元水あめ/, /転化糖/, /粉あめ/], 'sweetener', 'Sirup pati, halal.'),
  halalRule('malt', 'Malt / 麦芽', [/麦芽/, /モルト/], 'grain', 'Malt gandum, halal.'),
  halalRule('lactose', 'Lactose / 乳糖', [/乳糖/], 'dairy', 'Laktosa susu, halal.', 'medium'),
  halalRule('cocoa2', 'Cocoa / ココア', [/ココア/, /カカオ/], 'plant', 'Kakao, halal.'),
  halalRule('nuts', 'Nuts / ナッツ', [/ナッツ/, /アーモンド/, /落花生/, /ピーナッツ/, /カシューナッツ/], 'plant', 'Kacang-kacangan, halal.'),
  halalRule('raisin', 'Raisin / レーズン', [/レーズン/], 'plant', 'Kismis, halal.'),
  halalRule('egg-white', 'Egg white / 卵白', [/卵白/], 'animal', 'Putih telur, halal.', 'medium'),
  halalRule('yeast', 'Yeast / イースト', [/イースト/, /パン酵母/], 'additive', 'Ragi, halal.'),
  halalRule('noodle', 'Noodle / 麺', [/中華麺/, /油揚げ/, /めん/, /麺/], 'grain', 'Mi berbasis gandum, halal.'),
  halalRule('seaweed', 'Seaweed / 海藻', [/海藻/, /わかめ/, /昆布/, /のり/], 'plant', 'Rumput laut, halal.'),
  halalRule('mushroom', 'Mushroom / きのこ', [/きのこ/, /椎茸/, /しいたけ/, /エリンギ/, /しめじ/], 'plant', 'Jamur, halal.'),
  halalRule('konjac', 'Konjac / こんにゃく', [/こんにゃく/, /蒟蒻/], 'plant', 'Konnyaku, halal.'),
  halalRule('tofu', 'Tofu / 豆腐', [/豆腐/], 'plant', 'Tahu, halal.'),
  halalRule('chocolate', 'Chocolate / チョコ', [/チョコ/, /カカオマス/, /ココアバター/], 'plant', 'Cokelat; waspadai emulsifier/susu hewani.', 'low'),
  halalRule('biscuit', 'Biscuit / ビスケット', [/ビスケット/, /クッキー/, /ウエハース/, /ワッフル/], 'grain', 'Biskuit; waspadai shortening/margarin hewani.', 'low'),
  halalRule('pudding', 'Pudding / プリン', [/プリン/, /カスタード/], 'dessert', 'Puding (telur/susu); waspadai gelatin.', 'low'),
  halalRule('soup', 'Soup / スープ', [/スープ/], 'seasoning', 'Sup bubuk; umumnya halal, waspadai ekstrak hewani.', 'low'),
  {
    id: 'dressing',
    label: 'Dressing / ドレッシング',
    status: 'syubhat',
    confidence: 'low',
    category: 'condiment',
    patterns: [/ドレッシング/],
    reasoning: 'Dressing bisa mengandung alkohol (cuka/anggur) dan ekstrak hewani. Perlu verifikasi.',
    sources: [LPPOM, JAKIM],
  },

  // --- frequency-ranked OFF-JP ingredients (top unknown tokens) --------------
  halalRule('glycine', 'Glycine / グリシン', [/グリシン/], 'additive', 'Glisin (asam amino), halal.'),
  halalRule('trehalose', 'Trehalose / トレハロース', [/トレハロース/], 'sweetener', 'Trehalosa, halal.'),
  halalRule('sucralose', 'Sucralose / スクラロース', [/スクラロース/], 'sweetener', 'Sukralosa (sintetis), halal.'),
  halalRule('sugars', 'Sugars / 糖類', [/^糖類$/, /砂糖類/], 'sweetener', 'Gula, halal.'),
  halalRule('acesulfame', 'Acesulfame K / アセスルファムK', [/アセスルファム/], 'sweetener', 'Pemanis sintetis, halal.'),
  halalRule('sodium-acetate', 'Sodium acetate / 酢酸Na', [/酢酸na/, /酢酸ナトリウム/], 'additive', 'Natrium asetat, halal.'),
  halalRule('xanthan', 'Xanthan / キサンタン', [/キサンタン/], 'additive', 'Xanthan gum (fermentasi), halal.'),
  halalRule('stevia', 'Stevia / ステビア', [/ステビア/], 'sweetener', 'Stevia (nabati), halal.'),
  halalRule('brewed-vinegar', 'Brewed vinegar / 醸造酢', [/醸造酢/], 'fermented', 'Cuka fermentasi, halal.'),
  halalRule('niacin', 'Niacin / ナイアシン', [/ナイアシン/], 'additive', 'Niasin (vitamin), halal.'),
  halalRule('aspartame', 'Aspartame / アスパルテーム', [/アスパルテーム/], 'sweetener', 'Aspartam (asam amino), halal.'),
  halalRule('turmeric', 'Turmeric / ウコン', [/ウコン/], 'plant', 'Kunyit (nabati), halal.'),
  halalRule('baking-soda', 'Baking soda / 重曹', [/重曹/], 'additive', 'Soda kue (mineral), halal.'),
  halalRule('acetic-acid', 'Acetic acid / 酢酸', [/酢酸/], 'additive', 'Asam asetat, halal.'),
  halalRule('kcl', 'Potassium chloride / 塩化K', [/塩化k/, /塩化カリウム/], 'additive', 'Kalium klorida (mineral), halal.'),
  halalRule('carotenoid', 'Carotenoid / カロテノイド', [/カロチン/, /カロテン/, /カロテノイド/, /カロチノイド/], 'colorant', 'Karotenoid (nabati), halal.'),
  halalRule('potassium-sorbate', 'Potassium sorbate / ソルビン酸K', [/ソルビン酸k/, /ソルビン酸カリウム/], 'additive', 'Kalium sorbat, halal.'),
  halalRule('annatto', 'Annatto / アナトー', [/アナトー/], 'colorant', 'Annatto (nabati), halal.'),
  halalRule('red-koji', 'Red koji / 紅麹', [/紅麹/, /ベニコウジ/], 'additive', 'Koji merah (fermentasi), halal.'),
  halalRule('matcha', 'Matcha / 抹茶', [/抹茶/], 'plant', 'Matcha (teh), halal.'),
  halalRule('green-tea', 'Green tea / 緑茶', [/緑茶/], 'plant', 'Teh hijau, halal.'),
  halalRule('coffee', 'Coffee / コーヒー豆', [/コーヒー豆/, /コーヒー/], 'plant', 'Kopi, halal.'),
  halalRule('azuki', 'Azuki / 小豆', [/小豆/], 'plant', 'Kacang azuki, halal.'),
  halalRule('rice-uruchi', 'Rice / うるち米', [/うるち米/, /もち米/], 'plant', 'Beras, halal.'),
  halalRule('white-sugar', 'White sugar / 白砂糖', [/白砂糖/], 'sweetener', 'Gula putih, halal.'),
  halalRule('fruit', 'Fruit / 果実', [/果実/], 'plant', 'Buah, halal.'),
  halalRule('leek', 'Leek / ねぎ', [/ねぎ/, /ネギ/], 'plant', 'Bawang daun, halal.'),
  halalRule('parsley', 'Parsley / パセリ', [/パセリ/], 'plant', 'Peterseli, halal.'),
  halalRule('broccoli', 'Broccoli / ブロッコリー', [/ブロッコリー/], 'plant', 'Brokoli, halal.'),
  halalRule('lettuce', 'Lettuce / レタス', [/レタス/], 'plant', 'Selada, halal.'),
  halalRule('apple', 'Apple / りんご', [/りんご/, /リンゴ/], 'plant', 'Apel, halal.'),
  halalRule('orange', 'Orange / オレンジ', [/オレンジ/], 'plant', 'Jeruk, halal.'),
  halalRule('licorice', 'Licorice / 甘草', [/甘草/, /カンゾウ/], 'plant', 'Akar manis, halal.'),
  halalRule('mackerel', 'Mackerel / さば', [/さば/, /サバ/], 'animal', 'Ikan kembung, halal (hasil laut).'),
  halalRule('salmon', 'Salmon / さけ', [/さけ/, /サケ/, /鮭/], 'animal', 'Ikan salmon, halal (hasil laut).'),
  halalRule('shrimp', 'Shrimp / えび', [/えび/, /エビ/, /海老/], 'animal', 'Udang, halal (hasil laut).'),
  halalRule('squid', 'Squid / いか', [/いか/, /イカ/, /烏賊/], 'animal', 'Cumi, halal (hasil laut).'),
  halalRule('alginate', 'Alginate / アルギン酸', [/アルギン酸/], 'additive', 'Alginat rumput laut, halal.'),
  halalRule('gardenia', 'Gardenia / クチナシ', [/クチナシ/], 'colorant', 'Pewarna gardenia (nabati), halal.'),
  halalRule('paprika-color', 'Paprika colour / パプリカ色素', [/パプリカ/], 'colorant', 'Pewarna paprika (nabati), halal.'),
  halalRule('veg-color', 'Vegetable colour / 野菜色素', [/野菜色素/], 'colorant', 'Pewarna nabati, halal.'),
  halalRule('nitrite', 'Sodium nitrite / 亜硝酸Na', [/亜硝酸na/, /亜硝酸ナトリウム/], 'additive', 'Natrium nitrit (mineral), halal.'),
  halalRule('smoke', 'Smoke flavour / くん液', [/くん液/, /燻液/], 'additive', 'Cairan asap, halal.'),
  halalRule('phenylalanine', 'Phenylalanine', [/フェニルアラニン/], 'additive', 'Fenilalanin (asam amino), halal.'),
  halalRule('expanding2', 'Raising agent / 膨脹剤', [/膨脹剤/], 'additive', 'Pengembang, halal.'),
  halalRule('salt-cn', 'Salt / 食用盐', [/食用盐/], 'mineral', 'Garam, halal.'),
  halalRule('sweetener2', 'Sweetener / 甘味料', [/甘味料/], 'sweetener', 'Pemanis; umumnya halal, waspadai varian.', 'low'),
  halalRule('stabilizer', 'Stabilizer / 安定剤', [/安定剤/], 'additive', 'Penstabil; umumnya nabati/mikroba.', 'low'),
  halalRule('preservative2', 'Preservative / 保存料', [/保存料/], 'additive', 'Pengawet; umumnya halal (sorbat/benzoat).', 'low'),
  halalRule('coagulant', 'Coagulant / 凝固剤', [/凝固剤/], 'additive', 'Koagulan (mineral/asam), halal.', 'low'),
  halalRule('flavor-oil', 'Flavour oil / 香味油', [/香味油/], 'fat', 'Minyak aroma; umumnya nabati.', 'low'),
  halalRule('dairy', 'Dairy / 乳製品', [/乳製品/, /乳由来/], 'dairy', 'Produk susu; halal, waspadai enzim.', 'low'),
  halalRule('condensed-milk', 'Condensed milk / 加糖練乳', [/加糖練乳/, /練乳/], 'dairy', 'Susu kental manis, halal.', 'low'),
  halalRule('dairy-based', 'Dairy-based food', [/乳等を主要原料/], 'dairy', 'Pangan berbasis susu; halal, waspadai enzim.', 'low'),
  halalRule('oligosaccharide', 'Oligosaccharide / オリゴ糖', [/オリゴ糖/], 'sweetener', 'Oligosakarida, halal.'),
  halalRule('safflower', 'Safflower / 紅花', [/紅花/], 'colorant', 'Pewarna safflower (nabati), halal.'),
  halalRule('barley', 'Barley / 大麦', [/大麦/], 'grain', 'Jelai (nabati), halal.'),
  halalRule('ferment-starter', 'Fermentation starter / 発酵種', [/発酵種/], 'additive', 'Starter fermentasi, halal.', 'low'),
  halalRule('carrageenan2', 'Carrageenan / カラギナン', [/カラギナン/], 'additive', 'Karagenan rumput laut, halal.'),
  halalRule('milk-protein', 'Milk protein / 乳たん白', [/乳たん白/, /乳たんぱく/], 'dairy', 'Protein susu, halal.', 'low'),
  halalRule('mgcl', 'Magnesium chloride / 塩化Mg', [/塩化mg/, /塩化マグネシウム/], 'additive', 'Magnesium klorida (mineral), halal.'),
  halalRule('sucrose-ester', 'Sucrose ester / ショ糖エステル', [/ショ糖エステル/, /ショ糖脂肪酸/], 'additive', 'Ester sukrosa (nabati), halal.'),
  halalRule('skim-condensed', 'Skim condensed milk', [/脱脂濃縮乳/, /脱脂乳/], 'dairy', 'Susu skim, halal.', 'low'),
  halalRule('pumpkin', 'Pumpkin / かぼちゃ', [/かぼちゃ/, /カボチャ/], 'plant', 'Labu, halal.'),
  halalRule('spinach', 'Spinach / ほうれん草', [/ほうれん草/, /ホウレンソウ/], 'plant', 'Bayam, halal.'),
  halalRule('xylose', 'Xylose / キシロース', [/キシロース/], 'sweetener', 'Xilosa, halal.'),
  halalRule('crab', 'Crab / かに', [/かに/, /カニ/, /蟹/], 'animal', 'Kepiting, halal (hasil laut).'),
  halalRule('burdock', 'Burdock / ごぼう', [/ごぼう/, /ゴボウ/], 'plant', 'Burdock, halal.'),
  halalRule('hops', 'Hops / ホップ', [/ホップ/], 'plant', 'Hop (nabati), halal.'),
  {
    id: 'processed-fat',
    label: 'Processed fat / 油脂加工品',
    status: 'syubhat',
    confidence: 'low',
    category: 'fat',
    patterns: [/油脂加工品/, /油脂加工食品/, /加工油脂/, /粉末油脂/, /食用油脂/],
    reasoning: 'Lemak/minyak olahan bisa hewani (termasuk babi) atau nabati. Perlu verifikasi.',
    sources: [LPPOM, JAKIM],
  },
  // --- tail batch 2 (frequency-ranked) ---------------------------------------
  halalRule('rosemary', 'Rosemary extract / ローズマリー', [/ローズマリー/], 'additive', 'Ekstrak rosemary (nabati), halal.'),
  halalRule('asparagus', 'Asparagus / アスパラガス', [/アスパラガス/, /アスパラ/], 'plant', 'Asparagus, halal.'),
  halalRule('celery', 'Celery / セロリ', [/セロリ/], 'plant', 'Seledri, halal.'),
  halalRule('sulfite', 'Sulfite / 亜硫酸塩', [/亜硫酸/], 'additive', 'Sulfit (mineral), halal.'),
  halalRule('olive-oil', 'Olive oil / オリーブ油', [/オリーブ油/, /オリーブオイル/], 'fat', 'Minyak zaitun, halal.'),
  halalRule('mineral-water', 'Mineral water / 鉱水', [/鉱水/, /ミネラルウォーター/], 'mineral', 'Air mineral, halal.'),
  halalRule('mix-flour', 'Mixed flour / ミックス粉', [/ミックス粉/], 'grain', 'Campuran tepung; umumnya halal.', 'low'),
  halalRule('daikon', 'Daikon / だいこん', [/だいこん/, /ダイコン/, /大根/], 'plant', 'Lobak putih, halal.'),
  halalRule('black-tea', 'Black tea / 紅茶', [/紅茶/], 'plant', 'Teh hitam, halal.'),
  halalRule('watercress', 'Watercress / クレソン', [/クレソン/], 'plant', 'Selada air, halal.'),
  halalRule('peach', 'Peach / もも', [/もも/, /モモ/, /桃/], 'plant', 'Persik, halal.'),
  halalRule('arginine', 'Arginine / アルギニン', [/アルギニン/], 'additive', 'Arginin (asam amino), halal.'),
  halalRule('isoleucine', 'Isoleucine / イソロイシン', [/イソロイシン/], 'additive', 'Isoleusin (asam amino), halal.'),
  halalRule('napa', 'Napa cabbage / はくさい', [/はくさい/, /ハクサイ/, /白菜/], 'plant', 'Sawi putih, halal.'),
  halalRule('komatsuna', 'Komatsuna / 小松菜', [/小松菜/], 'plant', 'Komatsuna, halal.'),
  halalRule('rye', 'Rye / ライ麦', [/ライ麦/], 'grain', 'Gandum hitam, halal.'),
  halalRule('kale', 'Kale / ケール', [/ケール/], 'plant', 'Kale, halal.'),
  halalRule('gum-arabic', 'Gum arabic / アラビアガム', [/アラビアガム/], 'additive', 'Gum arab (nabati), halal.'),
  halalRule('sweet-potato', 'Sweet potato / さつまいも', [/さつまいも/, /サツマイモ/], 'plant', 'Ubi jalar, halal.'),
  halalRule('strawberry', 'Strawberry / いちご', [/いちご/, /イチゴ/, /苺/], 'plant', 'Stroberi, halal.'),
  halalRule('kinako', 'Kinako / きな粉', [/きな粉/, /きなこ/], 'plant', 'Tepung kedelai, halal.'),
  halalRule('rice-koji', 'Rice koji / 米こうじ', [/米こうじ/, /米麹/], 'additive', 'Koji beras (fermentasi), halal.'),
  halalRule('lysozyme', 'Lysozyme / リゾチーム', [/リゾチーム/], 'additive', 'Lisozim (umumnya dari putih telur), halal.', 'medium'),
  halalRule('arare', 'Arare / あられ', [/あられ/], 'grain', 'Kerupuk beras; umumnya halal.', 'low'),
  halalRule('nori', 'Nori / 海苔', [/海苔/, /のり/, /あおさ/], 'plant', 'Rumput laut, halal.'),
  halalRule('kombu', 'Kombu / こんぶ', [/こんぶ/, /コンブ/], 'plant', 'Kombu, halal.'),
  halalRule('walnut', 'Walnut / くるみ', [/くるみ/, /クルミ/, /胡桃/], 'plant', 'Kenari, halal.'),
  halalRule('garlic-powder', 'Garlic powder / ガーリック', [/ガーリック/], 'plant', 'Bawang putih bubuk, halal.'),
  halalRule('seasoning-granule', 'Seasoning / 調味顆粒', [/調味顆粒/], 'additive', 'Bumbu butiran; umumnya halal.', 'low'),
  {
    id: 'bacon',
    label: 'Bacon / ベーコン',
    status: 'haram',
    confidence: 'high',
    category: 'animal',
    patterns: [/ベーコン/],
    reasoning: 'Bacon umumnya dari daging babi, haram. (Bila dari sapi/ayam, tetap perlu sembelihan syar\'i.)',
    sources: ['QS Al-Baqarah 2:173', LPPOM],
  },
  {
    id: 'tare',
    label: 'Tare / たれ',
    status: 'syubhat',
    confidence: 'low',
    category: 'condiment',
    patterns: [/たれ/, /タレ/],
    reasoning: 'Saus tare bisa mengandung alkohol, kecap, atau ekstrak hewani. Perlu verifikasi.',
    sources: [LPPOM, JAKIM],
  },
  // --- tail batch 3 ----------------------------------------------------------
  halalRule('cauliflower', 'Cauliflower / カリフラワー', [/カリフラワー/], 'plant', 'Kembang kol, halal.'),
  halalRule('bell-pepper', 'Bell pepper / ピーマン', [/ピーマン/], 'plant', 'Paprika bell, halal.'),
  halalRule('oats', 'Oats / オーツ麦', [/オーツ麦/, /オートミール/], 'grain', 'Oat, halal.'),
  halalRule('anthocyanin', 'Anthocyanin / アントシアニン', [/アントシアニン/], 'colorant', 'Antosianin (nabati), halal.'),
  halalRule('inulin', 'Inulin / イヌリン', [/イヌリン/], 'additive', 'Inulin (nabati), halal.'),
  halalRule('sodium-benzoate', 'Sodium benzoate / 安息香酸Na', [/安息香酸na/, /安息香酸ナトリウム/], 'additive', 'Natrium benzoat, halal.'),
  halalRule('antifoam', 'Antifoam / 消泡剤', [/消泡剤/], 'additive', 'Antibusa (umumnya silikon/mineral), halal.', 'low'),
  halalRule('fermented-milk', 'Fermented milk / 発酵乳', [/発酵乳/], 'dairy', 'Susu fermentasi; halal, waspadai enzim.', 'low'),
  halalRule('milk-fat', 'Milk fat / 乳脂肪', [/乳脂肪/], 'dairy', 'Lemak susu, halal.', 'low'),
  halalRule('powdered-sugar', 'Powdered sugar / 粉糖', [/粉糖/, /粉砂糖/], 'sweetener', 'Gula bubuk, halal.'),
  halalRule('mochi-flour', 'Mochi flour / もち粉', [/もち粉/], 'grain', 'Tepung mochi, halal.'),
  halalRule('cooked-rice', 'Cooked rice / ご飯', [/ご飯/, /ごはん/], 'grain', 'Nasi, halal.'),
  halalRule('katsuobushi', 'Katsuobushi / 鰹節', [/鰹節/, /かつお節/], 'animal', 'Ikan cakalang kering, halal (hasil laut).'),
  halalRule('leucine', 'Leucine / ロイシン', [/ロイシン/], 'additive', 'Leusin (asam amino), halal.'),
  halalRule('valine', 'Valine / バリン', [/バリン/], 'additive', 'Valin (asam amino), halal.'),
  halalRule('drinking-water', 'Drinking water / 飲用水', [/饮用水/, /飲用水/], 'mineral', 'Air minum, halal.'),
  halalRule('green-leaf', 'Green leaf / グリーンリーフ', [/グリーンリーフ/], 'plant', 'Selada hijau, halal.'),
  {
    id: 'shochu',
    label: 'Shochu / 焼酎',
    status: 'haram',
    confidence: 'high',
    category: 'alcohol',
    patterns: [/焼酎/],
    reasoning: '焼酎 adalah minuman beralkohol (khamr), haram.',
    sources: ["QS Al-Maa'idah 5:90", LPPOM],
  },
  {
    id: 'potato-salad',
    label: 'Potato salad / ポテトサラダ',
    status: 'syubhat',
    confidence: 'low',
    category: 'condiment',
    patterns: [/ポテトサラダ/],
    reasoning: 'Salad kentang biasanya mengandung mayones; waspadai aditif/emulsifier.',
    sources: [LPPOM],
  },
  {
    id: 'western-liquor',
    label: 'Western liquor / 洋酒',
    status: 'haram',
    confidence: 'high',
    category: 'alcohol',
    patterns: [/洋酒/],
    reasoning: '洋酒 adalah minuman beralkohol (khamr), haram.',
    sources: ["QS Al-Maa'idah 5:90", LPPOM],
  },
  {
    id: 'enzyme',
    label: 'Enzyme / 酵素',
    status: 'syubhat',
    confidence: 'medium',
    category: 'enzyme',
    patterns: [/酵素/],
    reasoning: 'Enzim dapat berasal dari hewan (termasuk babi) atau mikroba. Perlu verifikasi.',
    sources: [LPPOM, JAKIM],
  },
  {
    id: 'gelling-agent',
    label: 'Gelling agent / ゲル化剤',
    status: 'syubhat',
    confidence: 'low',
    category: 'additive',
    patterns: [/ゲル化剤/],
    reasoning: 'Gelling agent bisa agar/pektin (halal) atau gelatin (bergantung sumber). Perlu verifikasi.',
    sources: [LPPOM, JAKIM],
  },
  {
    id: 'glazing-agent',
    label: 'Glazing agent / 光沢剤',
    status: 'syubhat',
    confidence: 'low',
    category: 'additive',
    patterns: [/光沢剤/],
    reasoning: 'Pelapis bisa lilin (halal) atau shellac (serangga). Perlu verifikasi.',
    sources: ['EFSA — E904', LPPOM],
  },
  {
    id: 'fat-spread',
    label: 'Fat spread / ファットスプレッド',
    status: 'syubhat',
    confidence: 'medium',
    category: 'fat',
    patterns: [/ファットスプレッド/],
    reasoning: 'Lemak olesan bisa berbasis hewani (termasuk babi) atau nabati.',
    sources: [LPPOM, JAKIM],
  },
  {
    id: 'caseinate',
    label: 'Sodium caseinate / カゼインNa',
    status: 'syubhat',
    confidence: 'medium',
    category: 'dairy',
    patterns: [/カゼインna/, /カゼインナトリウム/],
    reasoning: 'Kaseinat susu; halal bila susu halal & bebas enzim haram. Perlu verifikasi.',
    sources: [LPPOM, JAKIM],
  },
  {
    id: 'sorbitol2',
    label: 'Sorbitol / ソルビット',
    status: 'syubhat',
    confidence: 'medium',
    category: 'additive',
    patterns: [/ソルビット/],
    reasoning: 'Sorbitol umumnya dari glukosa, tetapi MUIS menandai E420 syubhah. Hati-hati.',
    sources: ['MUIS Food Additive Listing (2016)'],
  },
  {
    id: 'creaming-powder',
    label: 'Creaming powder / クリーミングパウダー',
    status: 'syubhat',
    confidence: 'low',
    category: 'dairy',
    patterns: [/クリーミングパウダー/],
    reasoning: 'Krimer bubuk bisa mengandung lemak hewani/emulsifier. Perlu verifikasi.',
    sources: [LPPOM, JAKIM],
  },
  {
    id: 'color-developer',
    label: 'Colour developer / 発色剤',
    status: 'halal',
    confidence: 'low',
    category: 'additive',
    patterns: [/発色剤/],
    reasoning: 'Pengembang warna (mis. nitrit) umumnya halal; dagingnya yang perlu dicek.',
    sources: ['EFSA — E250', LPPOM],
  },

  {
    id: 'generic-extract',
    label: 'Extract / エキス',
    status: 'syubhat',
    confidence: 'low',
    category: 'additive',
    patterns: [/エキス/],
    reasoning:
      'Ekstrak generik (nama tanpa sumber). Bisa nabati atau hewani; tanpa keterangan syubhat. (Ekstrak ragi/酵母エキス punya entri tersendiri = halal.)',
    sources: [LPPOM],
  },
];

/**
 * First matching rule for a normalized token, or null.
 * Rules are evaluated in array order (specific -> generic).
 */
export function matchRule(normalized: string): CurationRule | null {
  if (!normalized) return null;
  for (const rule of CURATION_RULES) {
    for (const p of rule.patterns) {
      if (p.test(normalized)) return rule;
    }
  }
  return null;
}

/** Turn a matched rule into a MatchResult for a raw token. */
export function ruleToMatch(rule: CurationRule, raw: string): MatchResult {
  const entry: IngredientEntry = {
    id: `rule:${rule.id}`,
    names: [raw],
    status: rule.status,
    confidence: rule.confidence,
    basis: rule.basis ?? 'japan-label-rule',
    reviewed: true,
    category: rule.category,
    reasoning: rule.reasoning,
    sources: rule.sources,
  };
  return { entry, matchedTerm: raw, score: 1, kind: 'exact' };
}
